commerce_payment.commerce_payment_gateway.plugin.commerce_sermepa:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_name:
      type: string
      label: 'The merchant name'
    merchant_code:
      type: string
      label: 'The merchant code'
    merchant_group:
      type: string
      label: 'The merchant group'
    merchant_password:
      type: string
      label: 'The merchant password'
    merchant_terminal:
      type: string
      label: 'The merchant terminal'
    merchant_paymethods:
      type: sequence
      label: 'The merchant payment methods'
      sequence:
        type: string
        label: 'Payment method'
    merchant_consumer_language:
      type: string
      label: 'The merchant consumer language'
    currency:
      type: integer
      label: 'The currency'
    transaction_type:
      type: string
      label: 'The merchant transaction type'
    instructions:
      type: text_format
      label: 'Payment instructions'
      translatable: true
